### ISSUE TITLE
Tests hang on perl 5.8.9 on Linux

### ISSUE THREAD

**Issue by DrHyde** [Test-More/Test2-Harness#46]
Failure appears to be when looking for .yath.rc, it keeps recursing forever up a directory, and another, and another, and so on. I attach a log that I cut off after a few goes around the loop, but well after it had started to try to recurse into /'s parent directory.
[test2-harness-on-5.8.9-output.log](https://github.com/Test-More/Test2-Harness/files/1496958/test2-harness-on-5.8.9-output.log)

This is testing against a fairly "vanilla" 5.8.9, with the only non-core modules in it being those required for running CPAN::Reporter. Given that on the same machine the tests pass on 5.10.1, I assume that you depend on a later version of some core module.

**Comment by exodist** [comment]
I just pushed what I *think* may fix this. There was a typo, the code had a 'next' when an eval failed instead of a 'last'.

I was not able to reproduce the problem locally with my own 5.8.9 installs, so I need you to verify if you can.

0.001035 was just uploaded to cpan, you should be able to install it with `cpanm --dev Test2::Harness` in an hour or so.

**Comment by DrHyde** [comment]
On Wed, Nov 22, 2017 at 06:02:42PM +0000, Chad Granum wrote:

> I just pushed what I *think* may fix this. There was a typo, the code had a 'next' when an eval failed instead of a 'last'.

Yep, that fixed it. Well, the tests now *complete* at least, failure
report incoming on the CPANtesters website :-)

-- 
David Cantrell | Enforcer, South London Linguistic Massive

  All principles of gravity are negated by fear
                                            -- Cartoon Law IV
